drop='~/Dropbox'
prog='~/git'
unc=$prog'/uncrumpled'
ezs=$drop'/linux_scripts'

# Programs
export DOTFILES = $HOME/dotfiles/dotfiles


# Programming
export XDG_CONFIG_HOME=$HOME/.config

alias p=python3


# Other
alias sir="grep-nr -e"
alias si="grep -n -e"
#alias sip="grep -n --include=\*.py -e"
